---
version: '2.4'

services:
  react-app:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:5000
      NODE_ENV: development
    volumes:
      - ./:/app
