---
version: '2.4'

services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/njs/:/etc/nginx/njs
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - 3000:80
    depends_on:
      - webpack

  webpack:
    build:
      context: .
      target: development
    volumes:
      - ./:/app

  # webpack:
  #   image: node:16-buster-slim
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   command: sh -c "npm install --force && ./node_modules/.bin/craco start"
