export const START_EXPENSES_LOADING = 'START_EXPENSES_LOADING';
export const STOP_EXPENSES_LOADING = 'STOP_EXPENSES_LOADING';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const UPDATE_EXPENSE_IMAGE = 'UPDATE_EXPENSE_IMAGE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const REMOVE_EXPENSE_IMAGE = 'REMOVE_EXPENSE_IMAGE';
export const SET_EXPENSES = 'SET_EXPENSES';
