export const SET_WALLET_LOADING = 'SET_WALLET_LOADING';
export const STOP_WALLET_LOADING = 'STOP_WALLET_LOADING';
export const ADD_WALLET = 'ADD_WALLET';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const REMOVE_WALLET = 'REMOVE_WALLET';
export const SET_CURRENT_WALLET = 'SET_CURRENT_WALLET';
export const SET_WALLETS = 'SET_WALLETS';
