---
version: '2.4'

services:
  node:
    build:
      context: .
      target: development
    ports:
      - 5000:5000
    environment:
      MONGODB_NAME: bitbudget
      MONGODB_USER: root
      MONGODB_PASSWORD: toor
      JWT_SECRET: d58573e8a27dc86c3df759b6b7eca1d3ef2059afd1732fa7e80b5eeea0f9f575
      JWT_EXPIRE: 3600
      PORT: 5000
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:5-focal
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: bitbudget

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
