version: '3.8'

services:
  node:
    image: folious/gadget-server:latest
    restart: always
    ports:
      - 3000:80
    environment:
      MONGO_URI: mongodb://root:toor@mongo:27017/gadget-server?authSource=admin
      JWT_SECRET: d58573e8a27dc86c3df759b6b7eca1d3ef2059afd1732fa7e80b5eeea0f9f575
      JWT_EXPIRE: 3600
  
  mongo:
    image: mongo:5-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: gadget-server

networks:
  proxy: {}