node {
  def commit_id

  stage('Preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"
    commit_id = readFile('.git/commit-id').trim()
  }

  stage('Test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'cd server'
      sh 'npm install'
      sh 'npm test'
    }
  }

  stage('Docker build and publish') {
    docker.withRegistry('https://index.docker.io/v2', 'dockerhub') {
      def app = docker.build("folious/gadget-budget-server:${commit_id}", '.').push()
    }
  }
}