export const START_USER_LOADING = 'START_USER_LOADING';
export const STOP_USER_LOADING = 'STOP_USER_LOADING';

export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
